language: rust
cache: cargo
rust: stable
os:
    - linux
# Travis doesn't have enough machines for this.
#   - osx    
    - windows
script:
    - cargo build -v
    - cargo test -v
branches:
    only: 
        - master