[package]
name = "crockford"
version = "1.0.0-beta.2"
authors = ["J/A <archer884@gmail.com>"]
license = "MIT/Apache-2.0"
description = """
Provides Crockford Base32 encoding for identifiers (e.g. u64 values).
"""

[dependencies]
