[package]
name = "crockford"
version = "1.0.0"
authors = ["J/A <archer884@gmail.com>"]
license = "MIT/Apache-2.0"
description = """
Provides Crockford 32-bit encoding for identifiers (e.g. u64 values).
"""

[dependencies]
